name: healthtracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+5

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  rxdart: ^0.27.3
  hive: ^2.1.0
  path_provider: ^2.0.9
  hive_flutter: ^1.1.0
  flutter_speed_dial: ^5.1.0
  shared_preferences: ^2.0.13
  fl_chart: ^0.50.6
  google_mobile_ads: ^1.2.0
  flutter_local_notifications: ^9.5.3+1
  numberpicker: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  test: ^1.16.8
  flutter_launcher_icons: ^0.9.2


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/glucose-meter.png
    - assets/blood-pressure.png

